"""Use-case-shaped persistence boundary for one project."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol


class ProjectStore(Protocol):
    def inspect_project_state(self) -> object: ...

    def create_or_replay_project(self, command: object) -> object: ...

    def get_project_summary(self, project_id: str) -> object: ...

    def get_experiment_trace(self, query: object) -> object: ...

    def begin_run(self, command: object) -> object: ...

    def mark_attempt_running(
        self, attempt_id: str, started_at: datetime, session_id: str
    ) -> None: ...

    def complete_attempt(self, command: object) -> object: ...

    def begin_validation(self, command: object) -> object: ...

    def mark_validation_running(self, validation_id: str, started_at: datetime) -> None: ...

    def complete_validation(self, command: object) -> object: ...

    def inspect_integrity(self, deep: bool) -> object: ...
